export const BOT_AUTOMATIC_LEAVE = {
	everyone_left_timeout: { timeout: 30 },
	bot_detection: {
		using_participant_names: {
			matches: [
				"notetaker",
				"note taker",
				"notes by",
				"recorder",
				"assistant",
				"copilot",
				"ai companion",
				"grain",
				"fellow",
				"tl;dv",
				"read.ai",
				"fathom",
				"fireflies",
				"otter.ai",
				"gemini",
				"meetgeek",
				"avoma",
				"sembly",
				"supernormal",
				"circleback",
				"granola",
				"bluedot",
			],
			activate_after: 120,
			timeout: 30,
		},
		using_participant_events: { activate_after: 300, timeout: 60 },
	},
	silence_detection: { activate_after: 1200, timeout: 600 },
} as const;
